# Generated by Django 3.1.1 on 2020-10-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouterDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapid', models.CharField(max_length=256)),
                ('hostname', models.CharField(max_length=256)),
                ('loopback', models.GenericIPAddressField()),
                ('mac_addr', models.CharField(max_length=256)),
                ('active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'router_details',
                'unique_together': {('loopback', 'hostname')},
            },
        ),
    ]
